name: '@ngworker/lumberjack-ivy CI'

env:
  # Must match the Angular version in `package.json`
  ANGULAR_CURRENT: 11.2.x
  # The latest Node.js version compatible with the Angular version listed in `package.json`
  NODE_CURRENT: 12.x
  NODE_OPTIONS: --max_old_space_size=6144

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ivy-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_CURRENT }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_CURRENT }}

      - name: Variable-Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-${{ env.NODE_CURRENT }}-angular-${{ env.ANGULAR_CURRENT }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_CURRENT }}-angular-${{ env.ANGULAR_CURRENT }}-yarn-
            ${{ runner.os }}-node-${{ env.NODE_CURRENT }}-angular-
      - run: yarn install
      - run: yarn enable-partial-ivy-compilation
      - run: yarn build:lib
      - uses: actions/upload-artifact@v2
        with:
          name: lumberjack-ivy-package
          path: dist/ngworker/lumberjack
          if-no-files-found: error

  ivy-app:
    runs-on: ubuntu-latest
    needs: ivy-build

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        angular-version: [11.1.x, 11.2.x]
        include:
          - angular-version: 12.0.x
            node-version: 12.x
          - angular-version: 12.0.x
            node-version: 14.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Angular version ${{ matrix.angular-version }}
        uses: ngworker/angular-versions-action@v4
        with:
          angular-version: ${{ matrix.angular-version }}

      - name: Variable-Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-yarn-
            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-
      - run: yarn install
      - run: yarn delete-path-alias @ngworker/lumberjack
      - run: yarn delete-path-alias @ngworker/lumberjack/console-driver
      - run: yarn delete-path-alias @ngworker/lumberjack/http-driver
      - uses: actions/download-artifact@v2
        with:
          name: lumberjack-ivy-package
          path: node_modules/@ngworker/lumberjack

      - run: yarn test:ci
      - run: yarn build
